name: flutter_sr
description: Savan Resorts Application.

publish_to: 'none'

version: 2.1.0+b20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  convex_bottom_bar: ^3.0.0
  dio: ^4.0.0
  flutter_svg: ^0.19.3
  intl: ^0.17.0
  flutter_form_builder: ^6.0.0
  provider: ^5.0.0
  get_it: ^4.0.2
  shared_preferences: ^2.0.5
  cached_network_image: ^2.5.1
  flutter_cached_pdfview: ^0.3.5
  shared_preferences_windows: ^2.0.0
  transparent_image: ^1.0.0
  badges: ^1.2.0
  webview_flutter: ^2.0.2
  bordered_text: ^1.0.1
  flutter_swiper: ^1.1.6
  flutter_html: ^0.11.1
  get: ^4.1.1
  double_back_to_close_app: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  path_provider: ^2.0.1
  path_provider_windows: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
